version: "3.2"

services:
  nacos:
    image: nacos/nacos-server:v2.1.0
    environment:
      MODE: standalone
    ports:
      - "8848:8848"
  mysql:
    image: mysql:5.7.25
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d/"
    ports:
      - "3306:3306"
  userservice:
    build: ./user-service
    ports:
      - "8081:8081"
  orderservice:
    build: ./order-service
    ports:
      - "8088:8088"
  feign:
    build: ./feign
  gateway:
    build: ./gateway
    ports:
      - "10010:10010"
  mq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: zjut
      RABBITMQ_DEFAULT_PASS: 123321
    ports:
      - "15672:15672"
      - "5672:5672"
